---
- name: add apt key (with http-proxy)
  apt_key:
    data: "{{ lookup('url', 'https://download.docker.com/linux/ubuntu/gpg', split_lines=False) }}"
  register: apt_key_with_proxy
  environment:
    HTTP_PROXY: "{{ openio_environment.http_proxy }}"
    HTTPS_PROXY: "{{ openio_environment.http_proxy }}"
  when:
    - openio_environment is defined
    - openio_environment.http_proxy is defined
  tags: install

- name: add apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  when: apt_key_with_proxy is skipped
  tags: install

- name: instal apt-transport-https
  package:
    name: apt-transport-https
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
  register: install_packages_https
  until: install_packages_https is success
  retries: 5
  delay: 2
  tags: install

- name: repository installation
  apt_repository:
    filename: docker-ce
    repo: "{{ openio_docker_repo_url }}"
    update_cache: true
  tags: install

- name: Install docker
  package:
    name: "{{ pkg }}"
    state: present
  with_items: "{{ openio_docker_packages }}"
  loop_control:
    loop_var: pkg
  ignore_errors: "{{ ansible_check_mode }}"
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
  tags: install

- name: Install docker-compose
  package:
    name: "{{ pkg }}"
    state: present
  with_items: "{{ openio_docker_compose_packages }}"
  loop_control:
    loop_var: pkg
  ignore_errors: "{{ ansible_check_mode }}"
  register: install_packages_compose
  until: install_packages_compose is success
  retries: 5
  delay: 2
  when: openio_docker_compose
  tags: install
...
