---
- name: Add Docker repository
  get_url:
    url: "{{ openio_docker_repo_url }}"
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: 0644
  tags: install

- name: Install docker
  package:
    name: "{{ pkg }}"
    state: present
  with_items: "{{ openio_docker_packages }}"
  loop_control:
    loop_var: pkg
  ignore_errors: "{{ ansible_check_mode }}"
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
  tags: install

- name: Install docker-compose
  package:
    name: "{{ pkg }}"
    state: present
  with_items: "{{ openio_docker_compose_packages }}"
  loop_control:
    loop_var: pkg
  ignore_errors: "{{ ansible_check_mode }}"
  register: install_packages_compose
  until: install_packages_compose is success
  retries: 5
  delay: 2
  when: openio_docker_compose
  tags: install
...
