---
- hosts: localhost
  become: true
  vars:
    openio_environment:
      http_proxy: ""
      https_proxy: ""
      no_proxy: ""

  roles:
    #- role: users
    - role: repository
      openio_repository_no_log: false
      openio_repository_mirror_host: mirror2.openio.io

    - role: role_under_test
...
